/**
 * Numin Local Memory Database Layer
 * Provides typed API wrappers for the local SQLite database
 * served by OpenClaw on port 3000 (/db/* endpoints).
 *
 * The actual SQLite runtime lives on OpenClaw (server side).
 * This file is the frontend client that reads/writes via REST.
 */

const DB_BASE = 'http://localhost:3000/db';

// ── Schema Types ──────────────────────────────────────────

export type AgentId = 'aria' | 'vance' | 'nexus' | 'prism' | 'apex' | 'numin';

export type ConversationEntry = {
    id: string;
    agent_id: AgentId;
    role: 'user' | 'assistant';
    content: string;
    timestamp: string;          // ISO 8601
    session_id: string;
    tags: string[];             // user-defined tags
    pinned: boolean;
    summary?: string;           // auto-generated by agent
};

export type BusinessMemoryEntry = {
    id: string;
    key: string;
    value: string;
    category: 'client' | 'preference' | 'rule' | 'contact' | 'other';
    created_at: string;
    updated_at: string;
    agent_id: AgentId;
};

export type AgentActivityEntry = {
    id: string;
    agent_id: AgentId;
    action_type: 'message' | 'automation' | 'integration_sync' | 'alert' | 'report';
    description: string;
    timestamp: string;
    metadata: Record<string, unknown>;
    status: 'completed' | 'in_progress' | 'failed';
};

export type KPIEntry = {
    id: string;
    metric_name: string;
    value: number;
    unit: string;
    timestamp: string;
    source_agent: AgentId;
};

export type ConversationFilters = {
    agent_id?: AgentId | AgentId[];
    from?: string;        // ISO date
    to?: string;          // ISO date
    query?: string;       // keyword search
    pinned?: boolean;
    tags?: string[];
    session_id?: string;
    limit?: number;
    offset?: number;
};

export type MemoryExportFormat = 'json' | 'csv' | 'pdf';

// ── Utility ──────────────────────────────────────────────

async function dbFetch<T>(path: string, opts?: RequestInit): Promise<T> {
    const res = await fetch(`${DB_BASE}${path}`, {
        headers: { 'Content-Type': 'application/json' },
        ...opts,
    });
    if (!res.ok) throw new Error(`Memory DB error ${res.status}: ${path}`);
    return res.json();
}

// ── Conversations ─────────────────────────────────────────

export const Conversations = {
    /** Fetch paginated conversation history with optional filters */
    list: (filters: ConversationFilters = {}): Promise<ConversationEntry[]> => {
        const params = new URLSearchParams();
        if (filters.agent_id) {
            const ids = Array.isArray(filters.agent_id) ? filters.agent_id : [filters.agent_id];
            ids.forEach(id => params.append('agent_id', id));
        }
        if (filters.from) params.set('from', filters.from);
        if (filters.to) params.set('to', filters.to);
        if (filters.query) params.set('q', filters.query);
        if (filters.pinned !== undefined) params.set('pinned', String(filters.pinned));
        if (filters.tags) filters.tags.forEach(t => params.append('tag', t));
        if (filters.session_id) params.set('session_id', filters.session_id);
        if (filters.limit) params.set('limit', String(filters.limit));
        if (filters.offset) params.set('offset', String(filters.offset));
        return dbFetch(`/conversations?${params.toString()}`);
    },

    /** Insert a new conversation message */
    create: (entry: Omit<ConversationEntry, 'id' | 'timestamp'>): Promise<ConversationEntry> =>
        dbFetch('/conversations', { method: 'POST', body: JSON.stringify(entry) }),

    /** Toggle pin status */
    pin: (id: string, pinned: boolean): Promise<void> =>
        dbFetch(`/conversations/${id}/pin`, { method: 'PATCH', body: JSON.stringify({ pinned }) }),

    /** Update tags on a conversation entry */
    tag: (id: string, tags: string[]): Promise<void> =>
        dbFetch(`/conversations/${id}/tags`, { method: 'PATCH', body: JSON.stringify({ tags }) }),

    /** Delete a conversation entry */
    delete: (id: string): Promise<void> =>
        dbFetch(`/conversations/${id}`, { method: 'DELETE' }),

    /** Export conversations as PDF, CSV, or JSON */
    export: async (format: MemoryExportFormat, filters?: ConversationFilters): Promise<Blob> => {
        const res = await fetch(`${DB_BASE}/conversations/export?format=${format}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(filters ?? {}),
        });
        return res.blob();
    },
};

// ── Business Memory ───────────────────────────────────────

export const BusinessMemory = {
    list: (category?: BusinessMemoryEntry['category']): Promise<BusinessMemoryEntry[]> => {
        const params = category ? `?category=${category}` : '';
        return dbFetch(`/memory${params}`);
    },

    upsert: (key: string, value: string, category: BusinessMemoryEntry['category'], agent_id: AgentId): Promise<BusinessMemoryEntry> =>
        dbFetch('/memory', { method: 'PUT', body: JSON.stringify({ key, value, category, agent_id }) }),

    delete: (id: string): Promise<void> =>
        dbFetch(`/memory/${id}`, { method: 'DELETE' }),
};

// ── Agent Activity ────────────────────────────────────────

export const AgentActivity = {
    list: (agent_id?: AgentId, limit = 50): Promise<AgentActivityEntry[]> => {
        const params = new URLSearchParams({ limit: String(limit) });
        if (agent_id) params.set('agent_id', agent_id);
        return dbFetch(`/activity?${params.toString()}`);
    },

    log: (entry: Omit<AgentActivityEntry, 'id' | 'timestamp'>): Promise<AgentActivityEntry> =>
        dbFetch('/activity', { method: 'POST', body: JSON.stringify(entry) }),
};

// ── KPI Data ──────────────────────────────────────────────

export const KPIs = {
    list: (metric_name?: string, limit = 100): Promise<KPIEntry[]> => {
        const params = new URLSearchParams({ limit: String(limit) });
        if (metric_name) params.set('metric_name', metric_name);
        return dbFetch(`/kpis?${params.toString()}`);
    },

    upsert: (entry: Omit<KPIEntry, 'id' | 'timestamp'>): Promise<KPIEntry> =>
        dbFetch('/kpis', { method: 'PUT', body: JSON.stringify(entry) }),
};

// ── Mock Data (for UI dev when OpenClaw is offline) ───────

export function getMockConversations(): ConversationEntry[] {
    return [
        { id: '1', agent_id: 'aria', role: 'user', content: 'What meetings do I have today?', timestamp: new Date(Date.now() - 3600000).toISOString(), session_id: 'sess-1', tags: ['calendar'], pinned: false },
        { id: '2', agent_id: 'aria', role: 'assistant', content: 'You have 3 meetings today: 9am standup, 11am client call with Procter & Gamble, and 2pm strategy review. I\'ve prepared briefings for each.', timestamp: new Date(Date.now() - 3500000).toISOString(), session_id: 'sess-1', tags: ['calendar'], pinned: true, summary: 'Today\'s schedule overview' },
        { id: '3', agent_id: 'vance', role: 'user', content: 'Update me on the Q1 pipeline.', timestamp: new Date(Date.now() - 7200000).toISOString(), session_id: 'sess-2', tags: ['crm', 'pipeline'], pinned: false },
        { id: '4', agent_id: 'vance', role: 'assistant', content: 'Q1 pipeline: 47 active deals, $2.3M total value. Top 3 at-risk: HealthTech Corp (70 days), Summit Retail (55 days), Blue Wave SaaS (48 days). Recommended action: priority outreach sequence.', timestamp: new Date(Date.now() - 7100000).toISOString(), session_id: 'sess-2', tags: ['crm', 'pipeline'], pinned: false, summary: 'Q1 pipeline health report' },
        { id: '5', agent_id: 'numin', role: 'user', content: 'Give me the full company status.', timestamp: new Date(Date.now() - 1800000).toISOString(), session_id: 'sess-3', tags: ['operations'], pinned: false },
        { id: '6', agent_id: 'numin', role: 'assistant', content: 'Business pulse: Revenue trending +18% MoM. ARIA flagged 2 priority emails. VANCE: 3 deals closing this week. NEXUS: Customer satisfaction 91%. PRISM: New campaign live. APEX: Fulfillment time down 12%. All systems operational.', timestamp: new Date(Date.now() - 1700000).toISOString(), session_id: 'sess-3', tags: ['operations', 'briefing'], pinned: true, summary: 'Full company status brief' },
    ];
}

export function getMockBusinessMemory(): BusinessMemoryEntry[] {
    return [
        { id: 'm1', key: 'Company Name', value: 'Acme Corp', category: 'other', created_at: new Date().toISOString(), updated_at: new Date().toISOString(), agent_id: 'numin' },
        { id: 'm2', key: 'Primary CRM', value: 'HubSpot', category: 'preference', created_at: new Date().toISOString(), updated_at: new Date().toISOString(), agent_id: 'vance' },
        { id: 'm3', key: 'Key Client: GlobalTech', value: 'CEO: James Harmon. Prefers email on Fridays. Contract renews June 2025.', category: 'client', created_at: new Date().toISOString(), updated_at: new Date().toISOString(), agent_id: 'aria' },
        { id: 'm4', key: 'Meeting Preference', value: 'Keep Tuesday mornings free. Max 4 meetings/day.', category: 'rule', created_at: new Date().toISOString(), updated_at: new Date().toISOString(), agent_id: 'aria' },
        { id: 'm5', key: 'Sales Process', value: 'Discovery → Demo → Proposal (5 days) → Close. Always CC legal on contract sends.', category: 'rule', created_at: new Date().toISOString(), updated_at: new Date().toISOString(), agent_id: 'vance' },
    ];
}

export function getMockKPIs(): KPIEntry[] {
    return [
        { id: 'k1', metric_name: 'Monthly Revenue', value: 284000, unit: 'USD', timestamp: new Date().toISOString(), source_agent: 'apex' },
        { id: 'k2', metric_name: 'Active Deals', value: 47, unit: 'count', timestamp: new Date().toISOString(), source_agent: 'vance' },
        { id: 'k3', metric_name: 'Customer Satisfaction', value: 91, unit: '%', timestamp: new Date().toISOString(), source_agent: 'nexus' },
        { id: 'k4', metric_name: 'Tasks Completed Today', value: 23, unit: 'count', timestamp: new Date().toISOString(), source_agent: 'apex' },
        { id: 'k5', metric_name: 'Open Support Tickets', value: 8, unit: 'count', timestamp: new Date().toISOString(), source_agent: 'nexus' },
        { id: 'k6', metric_name: 'Pipeline Value', value: 2300000, unit: 'USD', timestamp: new Date().toISOString(), source_agent: 'vance' },
    ];
}
